/*
 * 
 * argc = count parameter's number + 1 (program's name or path is fistr parameter)
 * argv[0] - ./program
 * #define CLI_INPUT "--entrada" argv[1] (if or loop) 
 * argv[2] - file.csv
 * #define CLI_OUTPUT "--saida" argv[4]
 * #define CLI_FILE_TYPE_CSV "--formato-csv" argv[5]
 * #define CLI_FILE_TYPE_TXT "--formato-txt" argv[5]
 * #define CLI_AVG_ENGAGED "--media-empenhado" argv[3] (if or loop)
 * #define CLI_AVG_SETTLED "--media-liquidado" argv[3] (if or loop)
 * #define CLI_AVG_PAID "--media-valor-pago" argv[3] (if or loop)
 * #define CLI_AVG_OVERALL "--media-geral" argv[3] (if or loop)
 * #define CLI_HELP "--ajuda" argv[1] (if or loop) 
 * 
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h> /* Enable use of the strdup */
 
#define BUFFER_SIZE 1024
#define MATRIX_SIZE_C 3
#define FIX_BUG_LINE "CÂMARA MUNICIPAL DE RIO CLARO"
#define CLI_INPUT "--entrada"
#define CLI_OUTPUT "--saida"
#define CLI_FILE_TYPE_CSV "--formato-csv"
#define CLI_FILE_TYPE_TXT "--formato-txt"
#define CLI_AVG_ENGAGED "--media-empenhado"
#define CLI_AVG_SETTLED "--media-liquidado"
#define CLI_AVG_PAID "--media-valor-pago"
#define CLI_AVG_OVERALL "--media-geral"
#define CLI_HELP "--ajuda"
#define VERSION "Sumarizador ATM2s2018"
#define PROGRAM_NAME "./sumarizador"
#define EXAMPLE_PATH_OR_FILE "./Downloads/consolidado_out2018.csv"


void get_values(char filter[], double l_values[]);
double strtodouble (char *str_result[BUFFER_SIZE], int position);
void print_screen_values(int line, int str_line, int column);
void average_overall(int line, int str_line, int column, char option);
void write_to_file_all(double avg_value_engaged, double avg_value_settled, double avg_value_paid, char type_file);
void write_to_file(double avg_value_x, char option, char type_file);
void help_message();

/* Global Array of Values */
double values[BUFFER_SIZE][MATRIX_SIZE_C];

/* Global Variable to chose averages */
char type_file = '0'; 

int main(int argc, char *argv[])
{
    FILE *fp; /* Pointer (File type) */
    char buffer[BUFFER_SIZE]; /* Swap Area to receive String generated by File */
    char *read_data[BUFFER_SIZE]; /* Array that allocates data from the "buffer" */
    char aux_read_data[BUFFER_SIZE][BUFFER_SIZE];
    int read_size = 0; /* Buffer size read */
    int line = 0; /* line counter */
    int index = 0; /* aux */
    int t_index = 0;
    double l_values[MATRIX_SIZE_C];
    char option = 0;
    int size_eol = (strlen(FIX_BUG_LINE));
    
    /* Variables, if you want to work on reading character, the character of array (optional) */
    char filter[BUFFER_SIZE][BUFFER_SIZE];
    char ch;
    int column = 0;
    int t_column = 0;
    int str_size = 0;
    int str_line = 0;
    int str_column = 0;
    int aux_i = 0;

  
    while(argc == 1)
    {
        fprintf(stderr, "\n\tFaca assim: %s --parametro [caminho/arquivo] ou %s %s\n\n", argv[0], argv[0], CLI_HELP);
    	return 1;
    }

    if ((strcmp(argv[1], CLI_HELP) != 0) && (strcmp(argv[1], CLI_INPUT) != 0))
    {
        fprintf(stderr, "\n\tFaca assim: %s --parametro [caminho/arquivo] ou %s %s\n\n", argv[0], argv[0], CLI_HELP);
        return 1;
    }


    if ((strcmp(argv[1], CLI_HELP) == 0))
    {
        help_message();
        return 1;    
    }
 
    if ((strcmp(argv[1], CLI_INPUT) == 0))
    { /* Start: Data manipulation routines */
        
        /* Condition: if file or path exists, will be open in read-mode "r" */
        if ((fp = fopen(argv[2], "r")) == NULL)
        {
            //perror("\n\t<path/file>");
            printf("\n\t[caminho/arquivo]: Caminho (diretorio) ou Arquivo nao encontrados ou omitidos\n\n");
            return 1;
        }
        
        /* Loop: getting line by line, and inserting into a array and after copied to another array */
        while (fgets(buffer, sizeof(buffer), fp) != NULL)
        {
            read_size = strlen(buffer);
            /* "strdup" from <strings.h> doing copy of pointer to pointer */
            read_data[index] = strdup(buffer);
            index++;
            line++;
        }
         
        /* 2 - Printing content allocated in the Array of Strings (char by char) */
        for(index = 0; index < line; index++)
        {
            str_column = strlen(read_data[index]);
            if (read_data[index][str_column - 31] == 'C')
                read_data[index][str_column - 31] = '\0';

            if (read_data[index][0] == '1')
            {
                for(column = 0; column < str_column; column++)
                {       
                    ch = read_data[index][column];
                    filter[t_index][column] = ch;
                }
                str_line++;
                t_index++;
            }
        }
        
        for(t_index = 0; t_index < str_line; t_index++)
        {
            str_column = strlen(filter[t_index]);        

            get_values(filter[t_index], l_values);
            for (column = 0; column < MATRIX_SIZE_C;column++)
            {
                values[t_index][column]= l_values[column];
            }      
        }
        
    } /* End: Data manipulation routines */

    if (argc <= 3)
    {
        print_screen_values(line, str_line, column);
        return 1;
    }
    else
    {
        while(argc > 3)
        {  /* Start: choice of averages */

            if ((strcmp(argv[3], CLI_AVG_ENGAGED) == 0))
            {
                option = '1';

                if (argc == 5)
                {
                   if ((strcmp(argv[4], CLI_OUTPUT) != 0))
                   {
                       fprintf(stderr, "\n\tParametro desconhecido ou nao digitado, use %s ou %s %s\n\n", CLI_OUTPUT, argv[0], CLI_HELP);
                       return 1;
                   }
                   
                   if ((strcmp(argv[4], CLI_OUTPUT) == 0) && (argc >= 5))
                   {   
                       fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                       return 1;
                   }
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_CSV) == 0)) 
                {
                    type_file = '1';
                    average_overall(line, str_line, column, option);
                    return 1;
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) == 0)) 
                {
                    type_file = '2';
                    average_overall(line, str_line, column, option);
                    return 1;
                }
                    
                if ((argc == 6) && ((strcmp(argv[5], CLI_FILE_TYPE_CSV) != 0) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) != 0))) 
                {
                    fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                    return 1;
                }

                average_overall(line, str_line, column, option);
                return 1;    
            }

            if ((strcmp(argv[3], CLI_AVG_SETTLED) == 0))
            {
                option = '2';

                if (argc == 5)
                {
                   if ((strcmp(argv[4], CLI_OUTPUT) != 0))
                   {
                       fprintf(stderr, "\n\tParametro desconhecido ou nao digitado, use %s ou %s %s\n\n", CLI_OUTPUT, argv[0], CLI_HELP);
                       return 1;
                   }
                   
                   if ((strcmp(argv[4], CLI_OUTPUT) == 0) && (argc >= 5))
                   {   
                       fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                       return 1;
                   }
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_CSV) == 0)) 
                {
                    type_file = '1';
                    average_overall(line, str_line, column, option);
                    return 1;
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) == 0)) 
                {
                    type_file = '2';
                    average_overall(line, str_line, column, option);
                    return 1;
                }
                    
                if ((argc == 6) && ((strcmp(argv[5], CLI_FILE_TYPE_CSV) != 0) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) != 0))) 
                {
                    fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                    return 1;
                }

                average_overall(line, str_line, column, option);
                return 1;    
            }

            if ((strcmp(argv[3], CLI_AVG_PAID) == 0))
            {
                option = '3';

                if (argc == 5)
                {
                   if ((strcmp(argv[4], CLI_OUTPUT) != 0))
                   {
                       fprintf(stderr, "\n\tParametro desconhecido ou nao digitado, use %s ou %s %s\n\n", CLI_OUTPUT, argv[0], CLI_HELP);
                       return 1;
                   }
                   
                   if ((strcmp(argv[4], CLI_OUTPUT) == 0) && (argc >= 5))
                   {   
                       fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                       return 1;
                   }
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_CSV) == 0)) 
                {
                    type_file = '1';
                    average_overall(line, str_line, column, option);
                    return 1;
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) == 0)) 
                {
                    type_file = '2';
                    average_overall(line, str_line, column, option);
                    return 1;
                }
                    
                if ((argc == 6) && ((strcmp(argv[5], CLI_FILE_TYPE_CSV) != 0) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) != 0))) 
                {
                    fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                    return 1;
                }

                average_overall(line, str_line, column, option);
                return 1;    
            }

            if ((strcmp(argv[3], CLI_AVG_OVERALL) == 0))
            {
                option = '4';

                if (argc == 5)
                {
                   if ((strcmp(argv[4], CLI_OUTPUT) != 0))
                   {
                       fprintf(stderr, "\n\tParametro desconhecido ou nao digitado, use %s ou %s %s\n\n", CLI_OUTPUT, argv[0], CLI_HELP);
                       return 1;
                   }
                   
                   if ((strcmp(argv[4], CLI_OUTPUT) == 0) && (argc >= 5))
                   {   
                       fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                       return 1;
                   }
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_CSV) == 0)) 
                {
                    type_file = '1';
                    average_overall(line, str_line, column, option);
                    return 1;
                }

                if ((argc == 6) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) == 0)) 
                {
                    type_file = '2';
                    average_overall(line, str_line, column, option);
                    return 1;
                }
                    
                if ((argc == 6) && ((strcmp(argv[5], CLI_FILE_TYPE_CSV) != 0) && (strcmp(argv[5], CLI_FILE_TYPE_TXT) != 0))) 
                {
                    fprintf(stderr, "\n\tObrigatoriamente necessario apos %s, o uso de %s ou %s. Em caso de duvida %s %s\n\n", CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT, argv[0], CLI_HELP);
                    return 1;
                }

                average_overall(line, str_line, column, option);
                return 1;    
            }

            if ((strcmp(argv[3], CLI_AVG_ENGAGED) != 0) || (strcmp(argv[3], CLI_AVG_SETTLED) != 0) || (strcmp(argv[3], CLI_AVG_PAID) != 0))  
            {
                printf("\n\tObrigatoriamente use %s, %s, %s ou %s. Em caso de duvida use %s %s\n\n", CLI_AVG_ENGAGED, CLI_AVG_SETTLED, CLI_AVG_PAID, CLI_AVG_OVERALL, argv[0], CLI_HELP);
                return 1;    
            }
            
        } /* End: choice of averages */
        return 1;
    }

    fclose(fp);
    return 0;
}

void get_values(char filter[], double l_values[])
{    
    int count = 0;
    char *space = strtok(filter, " ");
    char *str_result[BUFFER_SIZE];
    int aux_count;
    double value_engaged;
    double value_settled;
    double value_paid;

    while (space)
    {
        str_result[count] = space;
        space = strtok (NULL, " ");
        count++;
    }
    
    value_engaged = strtodouble(str_result, count - 3);   
    value_settled = strtodouble(str_result, count - 2);
    value_paid = strtodouble(str_result, count - 1);

    l_values[0] = value_engaged; 
    l_values[1] = value_settled;
    l_values[2] = value_paid;
}

double strtodouble (char *str_result[BUFFER_SIZE], int position)
{
    char temp[BUFFER_SIZE];
    int i, pos_temp = 0;

    for (i = 0; str_result[i] != '\0'; ++i)
    {
        if (str_result[position][i] == ',')
        { /* If it's comma exchange to dot */
            temp[pos_temp++] = '.';
        }
        else if (str_result[position][i] != '.')
        { /* If not dot, put the character */
            temp[pos_temp++] = str_result[position][i];
        }
    }
    temp[pos_temp] = '\0'; /* Add terminator "\0" */

    return atof(temp); /* Return converted "temp" */
}

void print_screen_values(int line, int str_line, int column)
{
    int aux_count = 0;
    system("clear");
    for(line = 0; line < str_line; line++)
    {
        if((aux_count == 0) || (aux_count == 40) || (aux_count == 80) || (aux_count == 120))
            printf("\n\t--> Listagem de Valores - Outubro 2018\n\tIndice\t\tValor Empenhado\t\tValor Liquidado\t\tValor Pago\n\t--------------------------------------------------------------------------\n");

        printf("\t%d", aux_count++);
        for(column = 0; column < MATRIX_SIZE_C; column++)
        {
            printf("\t\tR$ %2.2f ", values[line][column]);
        }
        printf("\n");
    }
    printf("\n\n");
}

void average_overall(int line, int str_line, int column, char option)
{
    double value_engaged = 0;
    double value_settled = 0;
    double value_paid = 0;
    double avg_value_engaged = 0;
    double avg_value_settled = 0;
    double avg_value_paid = 0;

   for(line = 0; line < str_line; line++)
   {
       for(column = 0; column < MATRIX_SIZE_C; column++)
       {
            if (column == 0)
                value_engaged = value_engaged + values[line][column];

            if (column == 1)
                value_settled = value_settled + values[line][column];

            if (column == 2)
                value_paid = value_paid + values[line][column];
       }
   }

   avg_value_engaged = (value_engaged / str_line);
   avg_value_settled = (value_settled / str_line);
   avg_value_paid = (value_paid / str_line);

   switch (option)
   {
        case '1':
            system("clear");
            if ((type_file != '1') && (type_file != '2'))
                printf("\n\n\t+\tMedia - Valor Empenhado\t\tR$ %2.2f\n\n", avg_value_engaged);

            if ((type_file == '1') || (type_file == '2'))
                write_to_file(avg_value_engaged, option, type_file);
            break;
        
        case '2':
            system("clear");
            if ((type_file != '1') && (type_file != '2'))
                printf("\n\n\t+\tMedia - Valor Liquidado\t\tR$ %2.2f\n\n", avg_value_settled);
            
            if ((type_file == '1') || (type_file == '2'))
                write_to_file(avg_value_settled, option, type_file);
            break;

        case '3':
            system("clear");
            if ((type_file != '1') && (type_file != '2'))
                printf("\n\n\t+\tMedia - Valor Pago\t\tR$ %2.2f\n\n", avg_value_paid);
            
            if ((type_file == '1') || (type_file == '2'))
                write_to_file(avg_value_paid, option, type_file);
            break;
        
        case '4':
            system("clear");
            if ((type_file != '1') && (type_file != '2'))
            {
                printf("\n");
                printf("\n\t+\tMedia - Valor Empenhado\t\tR$ %2.2f\n", avg_value_engaged);
                printf("\n\t+\tMedia - Valor Liquidado\t\tR$ %2.2f\n", avg_value_settled);
                printf("\n\t+\tMedia - Valor Pago\t\tR$ %2.2f\n", avg_value_paid);
                printf("\n");
            }
            
            if ((type_file == '1') || (type_file == '2'))
                write_to_file_all(avg_value_engaged, avg_value_settled, avg_value_paid, type_file);
            break;
   
        default:
            system("clear");
            printf("\n\n\t+\tErro... \n\n");
            break;
   }
}

void write_to_file_all(double avg_value_engaged, double avg_value_settled, double avg_value_paid, char type_file)
{
    FILE * fp_w; /* Pointer (File type) */
    char *file_type_name = "\0"; /* Pointer to storage file name and file type */

    /* Checking file type */
    if (type_file == '1') 
        file_type_name = "arquivo.csv";
    
    if (type_file == '2') 
        file_type_name = "arquivo.txt";

    /* Create / Open file in w (write) mode */
    if ((fp_w = fopen(file_type_name, "w")) == NULL)
    {
        /* If file was not cretated */
        printf("\nNao foi possivel criar o Arquivo %s.\n\n", file_type_name);
        exit(EXIT_FAILURE);
    }

    /* Generating file in csv format */
    if (type_file == '1')
    {
        fprintf(fp_w, "\nMedias Gerais\n");
        fprintf(fp_w, "\n\t,+,\t,Media - Valor Empenhado,\t,\t,R$,%2.2f\n", avg_value_engaged);
        fprintf(fp_w, "\n\t,+,\t,Media - Valor Liquidado,\t,\t,R$,%2.2f\n", avg_value_settled);
        fprintf(fp_w, "\n\t,+,\t,Media - Valor Pago,\t,\t,R$,%2.2f\n", avg_value_paid);
        fprintf(fp_w, "\n");
    }
    
    /* Generating file in txt format */
    if (type_file == '2')
    {
        fprintf(fp_w, "\nMedias Gerais\n");
        fprintf(fp_w, "\n\t+\tMedia - Valor Empenhado\t\tR$ %2.2f\n", avg_value_engaged);
        fprintf(fp_w, "\n\t+\tMedia - Valor Liquidado\t\tR$ %2.2f\n", avg_value_settled);
        fprintf(fp_w, "\n\t+\tMedia - Valor Pago\t\tR$ %2.2f\n", avg_value_paid);
        fprintf(fp_w, "\n");
    }
    
    /* Closing file and saving data */
    fclose(fp_w);

    /* Success message */
    printf("\n\tArquivo %s criado com Sucesso\n\n", file_type_name);

}

void write_to_file(double avg_value_x, char option, char type_file)
{
    FILE * fp_w; /* Pointer (File type) */
    char *file_type_name = "\0"; /* Pointer to storage file name and file type */
    char *file_type_option = "\0"; /* Pointer to storage type option */

    /* Checking file type */
    if (type_file == '1') 
        file_type_name = "arquivo.csv";
    
    if (type_file == '2') 
        file_type_name = "arquivo.txt";

    /* Checking option type */
    if (option == '1') 
        file_type_option = "Media - Valor Empenhado";
    
    if (option == '2') 
        file_type_option = "Media - Valor Liquidado";

    if (option == '3') 
        file_type_option = "Media - Valor Pago";
    
    /* Create / Open file in w (write) mode */
    if ((fp_w = fopen(file_type_name, "w")) == NULL)
    {
        /* If file was not cretated */
        printf("\nNao foi possivel criar o Arquivo %s.\n\n", file_type_name);
        exit(EXIT_FAILURE);
    }

    /* Generating file in csv format */
    if (type_file == '1')
    {
        fprintf(fp_w, "\n%s\n", file_type_option);
        fprintf(fp_w, "\n\t,+,\t,Media - Valor Empenhado,\t,\t,R$,%2.2f\n", avg_value_x);
        fprintf(fp_w, "\n");
    }
    
    /* Generating file in txt format */
    if (type_file == '2')
    {
        fprintf(fp_w, "\n%s\n", file_type_option);
        fprintf(fp_w, "\n\t+\tMedia - Valor Empenhado\t\tR$ %2.2f\n", avg_value_x);
        fprintf(fp_w, "\n");
    }
    
    /* Closing file and saving data */
    fclose(fp_w);

    /* Success message */
    printf("\n\tArquivo %s criado com Sucesso\n\n", file_type_name);
}

void help_message()
{
    system("clear");
    printf("\n\tArea de Ajuda - Programa %s.\n", VERSION);

    printf("\n\tLista de Opcoes:");
    printf("\n\t\t%s\t\t\t\tImprime na tela mensagem de ajuda.", CLI_HELP);
    printf("\n\t\t%s\t\t\tOpcao obrigatoria para receber [caminho/arquivo].", CLI_INPUT);
    printf("\n\t\t%s\t\tImprime na tela Media Empenhada.", CLI_AVG_ENGAGED);
    printf("\n\t\t%s\t\tImprime na tela Media Liquidado.", CLI_AVG_SETTLED);
    printf("\n\t\t%s\t\tImprime na tela Media Empenhada.", CLI_AVG_ENGAGED);
    printf("\n\t\t%s\t\tImprime na tela Media Valor Pago.", CLI_AVG_PAID);
    printf("\n\t\t%s\t\t\tImprime na tela Media Geral.", CLI_AVG_OVERALL);
    printf("\n\t\t%s\t\t\t\tOpcao obrigatoria para imprimir as Medias em Arquivo.", CLI_OUTPUT);
    printf("\n\t\t%s\t\t\tImprime em Arquivo (arquivo.csv) a media repassada.", CLI_FILE_TYPE_CSV);
    printf("\n\t\t%s\t\t\tImprime em Arquivo (arquivo.txt) a media repassada.", CLI_FILE_TYPE_TXT);
    printf("\n");

    printf("\n\tExemplos de uso: ");
    printf("\n\t\t%s %s %s", PROGRAM_NAME, CLI_INPUT, EXAMPLE_PATH_OR_FILE);
    printf("\n\t\t%s %s %s %s", PROGRAM_NAME, CLI_INPUT, EXAMPLE_PATH_OR_FILE, CLI_AVG_OVERALL);
    printf("\n\t\t%s %s %s %s %s %s", PROGRAM_NAME, CLI_INPUT, EXAMPLE_PATH_OR_FILE, CLI_AVG_PAID, CLI_OUTPUT, CLI_FILE_TYPE_CSV);
    printf("\n\t\t%s %s", PROGRAM_NAME, CLI_HELP);
    printf("\n");

    printf("\n\tUso: %s %s", PROGRAM_NAME, CLI_HELP);
    printf("\n\t\tImprime mensagem de Ajuda na tela. Nao requer outro opcao.");
    printf("\n\n\tUso: %s %s [caminho/arquivo]", PROGRAM_NAME, CLI_INPUT);
    printf("\n\t\tAbre arquivo e imprime valores na tela. Uso obrigatório da opcao [%s] antes do arquivo a ser lido.", CLI_INPUT);
    printf("\n\n\tUso: %s %s [caminho/arquivo] %s ou %s ou %s ou %s", PROGRAM_NAME, CLI_INPUT, CLI_AVG_ENGAGED, CLI_AVG_SETTLED, CLI_AVG_PAID, CLI_AVG_OVERALL);
    printf("\n\t\tImprime a Media na tela (correspondente a opcao solicitada / tipo de media)");
    printf("\n\n\tUso: %s %s [caminho/arquivo] [alguma opcao de media] %s %s ou %s", PROGRAM_NAME, CLI_INPUT, CLI_OUTPUT, CLI_FILE_TYPE_CSV, CLI_FILE_TYPE_TXT);
    printf("\n\t\tImprime a Media em um arquivo nas pasta local (correspondente a opcao solicitada / tipo de arquivo)");
    printf("\n\n");

    printf("\n\n\tPressione qualquer tecla para sair");
    getchar();
    system("clear");
}